project:
  type: website
  output-dir: docs

website:
  title: "stepcareweb"
  navbar:
    logo: "img/stepcare_logo_box.png"
    left:
      - href: index.qmd
        text: Home
      - href: neuro.qmd
        text: Neuro
      - href: complete.qmd
        text: Data Completeness
      - href: baseline.qmd
        text: Baseline
      - about.qmd
       
      


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    

editor: visual

